In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
import copy
import pandas

In [2]:
x = np.asarray(range(15)).reshape((3, 5))

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
x.shape

(3, 5)

In [5]:
np.shape(x)

(3, 5)

In [10]:
np.amax(x, axis=0)

array([10, 11, 12, 13, 14])

In [65]:
class node:
        def __init__(self, val, depth):
            self.plane = val
            self.depth = depth 

class leaf(node):
    def __init__(self, ind, depth):
        self.ind = ind
        super().__init__(None, depth)

In [66]:
a = node(1, 2)

In [67]:
a.plane, a.depth

(1, 2)

In [68]:
b = leaf(np.arange(12), 2)

In [71]:
b.plane

In [28]:
def split(arr):
    m = np.median(arr)
    return arr[arr<=m], arr[arr>m]

In [29]:
split(a)

(array([45, 47, 24, 36, 12, 41, 49, 14]),
 array([86, 86, 81, 55, 58, 71, 90, 82]))

In [31]:
5 % 4

1

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [127]:
ind = np.array([0, 2])

In [128]:
x[ind, 1]

array([12, 11])

In [125]:
def split(data, ind, med, ax):
        left = ind[data[ind, ax] < med]
        mid = ind[data[ind, ax] == med]
        right = ind[data[ind, ax] > med]
        left = np.concatenate((left, mid[:(len(mid)+1)//2]))
        right = np.concatenate((mid[(len(mid)+1)//2:], right))
        return left, right

In [129]:
split(x, ind, 11.5, 1)

(array([2]), array([0]))

In [116]:
ind[:(1+len(ind))//2]

array([0, 1])

In [59]:
type(x)

numpy.ndarray

In [72]:
def true_closest(X_train, X_test, k):
    result = []
    for x0 in X_test:
        bests = list(sorted([(i, np.linalg.norm(x - x0)) for i, x in enumerate(X_train)], key=lambda x: x[1]))
        bests = [i for i, d in bests]
        result.append(bests[:min(k, len(bests))])
    return result    

In [73]:
X_train = np.random.randn(100, 3)
X_test = np.random.randn(10, 3)

In [74]:
true = true_closest(X_train, X_test, k=4)

In [75]:
true

[[19, 76, 84, 77],
 [83, 58, 84, 28],
 [73, 51, 67, 18],
 [52, 83, 84, 33],
 [81, 14, 72, 50],
 [96, 48, 20, 3],
 [0, 8, 94, 55],
 [46, 60, 97, 82],
 [84, 74, 77, 1],
 [86, 24, 1, 31]]

In [76]:
X_test

array([[-1.31865808,  0.60751553, -0.61186251],
       [-2.10307819, -1.01745962, -0.14930385],
       [ 0.98053761,  1.12065569,  0.97242177],
       [-2.22494027,  0.97041505,  0.17992118],
       [ 0.34793753,  0.52143152, -1.30494675],
       [ 0.41804955, -1.04015301,  0.36352882],
       [ 0.11386817,  0.1380686 ,  1.56917362],
       [ 0.01611493,  1.04785669, -0.20897182],
       [-1.42004513, -0.35901199,  0.32256324],
       [-0.54690656,  0.67628205,  0.73623684]])

In [77]:
tr = np.ones((3, 4))

In [78]:
tr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
tr[0] = np.zeros(2)

ValueError: could not broadcast input array from shape (2) into shape (4)

In [82]:
np.round(0.6)

1.0

In [83]:
import sys

In [86]:
sys.setrecursionlimit(10000)

In [87]:
sys.getrecursionlimit()

10000

In [88]:
def read_spam_dataset(path_to_csv):
    dtf =  pandas.read_csv(path_to_csv).sample(frac=1)
    return np.array(dtf.values[:,1:]).astype(float) , np.array(dtf["label"]).astype(int)

In [89]:
a = read_spam_dataset("spam.csv")

In [93]:
a[1].shape

(4601,)

In [92]:
a[0]

array([[0.00e+00, 0.00e+00, 0.00e+00, ..., 1.20e+01, 1.60e+01, 0.00e+00],
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 6.00e+00, 2.30e+01, 0.00e+00],
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 7.00e+01, 2.65e+02, 0.00e+00],
       ...,
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 4.10e+01, 7.90e+01, 1.00e+00],
       [0.00e+00, 6.50e-01, 0.00e+00, ..., 2.30e+01, 1.35e+02, 1.00e+00],
       [2.50e-01, 0.00e+00, 0.00e+00, ..., 3.20e+01, 2.10e+02, 1.00e+00]])