In [2]:
import numpy as np
import cv2

In [3]:
a = np.random.randint(-10, 10, (4, 5))

In [4]:
a

array([[  5,   2,  -1,  -4,   2],
       [  3,  -3, -10,   7,   9],
       [  8,  -9,  -6,  -6,   8],
       [ -6,  -5,  -5,  -8,   7]])

In [5]:
maxs = np.max(a, axis=0)
mins = np.min(a, axis=0) 

In [7]:
r = np.random.rand(2, a.shape)

In [11]:
r = r*(maxs-mins)+mins

In [12]:
r

array([[ 4.88174287, -0.90430261, -1.82679806,  1.93928218,  6.97288168],
       [-5.06190971, -2.35633773, -8.89852705,  6.30799193,  3.48569198]])

In [13]:
dist = np.linalg.norm(a[0]-r)

In [189]:
r[0] = a[1]

In [19]:
np.linalg.norm(a[0]-r, axis=1)

array([ 8.31487694, 17.06072723])

In [21]:
np.linalg.norm((a[0]-r)[1])

17.060727226964193

In [24]:
d = np.array(map(lambda x:np.linalg.norm(x), a))

In [25]:
d

array(<map object at 0x10c88ba58>, dtype=object)

In [26]:
def f(v):
    return np.linalg.norm(v)

In [28]:
ff = np.vectorize(f)

In [153]:
d = np.apply_along_axis(lambda v: np.linalg.norm(v-r, axis=1), 1, a)

In [154]:
c = np.min(d, axis=1)**2

In [155]:
np.sum(a[c==1], axis=0)/np.sum(c==1)

/Users/faridbag/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan])

In [160]:
c

array([195.        ,  97.50840012,   0.        , 218.        ])

In [176]:
cc = np.cumsum(c)
cc

array([195.        , 292.50840012, 292.50840012, 510.50840012])

In [177]:
cc = cc/cc[-1]
cc

array([0.38197217, 0.57297471, 0.57297471, 1.        ])

In [188]:
for i in range(10000):
    k = np.random.rand()
    if np.searchsorted(cc, k) == 0:
        print(k)

0.17255325890425444
0.04327060647456271
0.27963418536281026
0.03910221861779284
0.18561900931466901
0.3656020607034901
0.19816892981619316
0.28402014331251046
0.2524028477922903
0.10126908000372958
0.10114049786587798
0.1867556147516629
0.30194825792623425
0.004384475762396534
0.23147343324159364
0.27768193352925863
0.152121633685521
0.35123048055681894
0.2685059223941676
0.0899997956565225
0.21645301841587605
0.34932461252177804
0.09899626645229787
0.3221793696214178
0.3448828115059325
0.32717917257243445
0.3121844746099922
0.12761356589062156
0.05024011896958924
0.09608851151750997
0.04207282031660131
0.3527490818154484
0.07486810131056698
0.09200932499943804
0.3239270242255893
0.37207827441149266
0.06895190757773872
0.05018023626036794
0.2144330584805365
0.32286662435735114
0.3209660137458732
0.09034719385934087
0.18754781999001824
0.2621450253454668
0.1462784129432233
0.06351073641318106
0.007402569270306025
0.18864132251291998
0.21656482678336353
0.229279334370592
0.29922137943894

0.07648086630365247
0.2690344196016675
0.24302542350685985
0.18118377664482133
0.22540297620535243
0.08339038509700303
0.025581462030868307
0.18057584666014137
0.30365220177343655
0.346636347832312
0.2780070249275606
0.3109740155023395
0.11194673834199864
0.17778391112836334
0.3571076240224429
0.07597959296735446
0.06655779941071516
0.015441384906396793
0.08431231987748422
0.01765378635545345
0.003805104250749314
0.07794223071354223
0.33079551307923727
0.11991645739986223
0.2173044238824372
0.1864489223692456
0.06496963127111144
0.1865300425014048
0.0738068388833617
0.08026264034426067
0.3210966810545749
0.26459172116177465
0.32604916246175053
0.18628953174950968
0.3026028723029497
0.15061278705721937
0.14972844449138079
0.26485066471578766
0.11008750626216746
0.3144878045005961
0.01988577893962784
0.2346061086854695
0.05246889310007308
0.337799795223244
0.17389110951878461
0.2006588885059899
0.14577494166402072
0.15767039640107483
0.07030821735809245
0.08566463556300474
0.354705766757

0.08439311955386752
0.240018289311412
0.11044285427193723
0.06609565373208004
0.05757783772839564
0.28866698599309026
0.24773998021192045
0.00704552805478742
0.2538886800582746
0.3205233959964864
0.3049615084229639
0.011743886024061734
0.3492878742804948
0.07325765951394048
0.10757964141203946
0.2590302352905892
0.36246578899272774
0.016140900864123453
0.055956177545387065
0.3492624415446969
0.12900993523762705
0.19716538294772357
0.06947251629663431
0.2620266607324505
0.3004073895709557
0.06456773777274549
0.09678656605889302
0.2117847630962919
0.13226647966420668
0.12875763863514633
0.14364019037278342
0.2845301820234898
0.002046060642112213
0.3595218829106238
0.17450604139686898
0.3132092392739043
0.08948044812351397
0.09799190528198798
0.007537855843053665
0.24237130588767342
0.11797794192850586
0.12825111618698404
0.12187246620760495
0.1428455808991016
0.20999488722431714
0.252775692797262
0.03777727420550292
0.07120417732441342
0.19635529843341748
0.3167130154310075
0.07165479807

In [50]:
a[c==1]

array([[  3,  -3, -10,   7,   9],
       [ -6,  -5,  -5,  -8,   7]])

In [57]:
        def recount_centroid(j, ind):
            am = np.sum(ind==j)
            if am == 0:
                return np.random.rand(self.k, X.shape[1]) * (maxs - mins) + mins
            return np.sum(a[ind==j], axis=0)/ am

In [69]:
recount_centroid(0, c)

array([ 6.5, -3.5, -3.5, -5. ,  5. ])

In [60]:
t = np.arange(0, 2)

In [61]:
res = recount_centroid(t, c)

/Users/faridbag/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  


NameError: name 'self' is not defined

In [73]:
res = np.apply_along_axis(lambda v: recount_centroid(v, c), 1, t.reshape(2, 1))

In [74]:
res

array([[ 6.5, -3.5, -3.5, -5. ,  5. ],
       [-1.5, -4. , -7.5, -0.5,  8. ]])

In [70]:
t

array([0, 1])

In [75]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [76]:
0 in t

True

In [77]:
6.5 in res

True

In [96]:
a[np.random.choice(a.shape[0], 2, replace=False)]

array([[ -6,  -5,  -5,  -8,   7],
       [  3,  -3, -10,   7,   9]])

In [97]:
a[np.random.choice(a.shape[0], 2, replace=False), :]

array([[ 8, -9, -6, -6,  8],
       [-6, -5, -5, -8,  7]])

In [190]:
r

array([[  3.        ,  -3.        , -10.        ,   7.        ,
          9.        ],
       [ -5.06190971,  -2.35633773,  -8.89852705,   6.30799193,
          3.48569198]])

In [191]:
r = np.vstack((r, a[3]))

In [192]:
r

array([[  3.        ,  -3.        , -10.        ,   7.        ,
          9.        ],
       [ -5.06190971,  -2.35633773,  -8.89852705,   6.30799193,
          3.48569198],
       [ -6.        ,  -5.        ,  -5.        ,  -8.        ,
          7.        ]])

In [193]:
a[3]

array([-6, -5, -5, -8,  7])

In [194]:
def read_image(path):
    im = cv2.imread(path)
    return im[:,:,::-1]

def show_image(image):
    plt.figure(figsize=np.array(image.shape[:-1]) / 50)
    plt.imshow(image)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

def save_image(image, path):
    cv2.imwrite(path, image[:,:,::-1])

In [200]:
a = read_image("./image.png")
b = read_image("./image.png")

In [199]:
a[0,0]

array([225, 166, 152], dtype=uint8)

In [203]:
a = a.reshape(a.shape[0]*a.shape[1], a.shape[2])

In [204]:
a.shape

(221796, 3)

In [205]:
a[0]

array([225, 166, 152], dtype=uint8)

In [206]:
c = a.reshape(b.shape[0], b.shape[1], b.shape[2])

In [208]:
c.equals(b)

AttributeError: 'numpy.ndarray' object has no attribute 'equals'

In [209]:
np.array_equal(c, b)

True

In [211]:
a

array([[225, 166, 152],
       [222, 163, 149],
       [220, 161, 147],
       ...,
       [ 54,  43,  47],
       [ 53,  42,  46],
       [ 51,  40,  44]], dtype=uint8)

In [228]:
a = np.arange(0, 18).reshape(3, 3, 2)

In [225]:
c = a.reshape(9, 2)
b = np.array([[1, 2], [2, 1], [2,2]])

In [221]:
ind = np.array([0, 2 ,1]*3)

In [222]:
b[ind].reshape(3, 3 ,2)

array([[[1, 2],
        [2, 2],
        [2, 1]],

       [[1, 2],
        [2, 2],
        [2, 1]],

       [[1, 2],
        [2, 2],
        [2, 1]]])

In [229]:
a.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [230]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [48]:
a = np.random.rand(10, 3)

In [11]:
c, d = [0, 1, 2], [3, 4, 5, 6]

In [12]:
a[c], a[d]

(array([[0.29829559, 0.71307152, 0.58362113],
        [0.42356157, 0.49031396, 0.14125867],
        [0.83224221, 0.17190425, 0.6658959 ]]),
 array([[0.3187089 , 0.43613344, 0.73163297],
        [0.73223668, 0.44159376, 0.84440065],
        [0.28619879, 0.64735322, 0.23306334],
        [0.35804288, 0.67271727, 0.68425888]]))

In [15]:
np.mean(np.apply_along_axis(lambda v: np.linalg.norm(v-a[c], axis=1), 1, a[d]))

0.4999223945347155

In [17]:
set(range(a.shape[0]))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [18]:
d = {}

In [19]:
d[1, 2]=1

In [27]:
d

{(1, 2): 1, (2, 1): 2, (0, 0): 100}

In [21]:
d[2, 1] = 2

In [24]:
d[0,0] = 100

In [26]:
min(d, key=d.get)

(1, 2)

In [28]:
for i in d:
    print(i)

(1, 2)
(2, 1)
(0, 0)


In [30]:
dict(range(3), 0)

TypeError: dict expected at most 1 arguments, got 2

In [31]:
from collections import defaultdict

In [37]:
a = defaultdict(lambda:0)

In [38]:
a[1]

0

In [39]:
a

defaultdict(<function __main__.<lambda>()>, {1: 0})

In [51]:
d = {i:[i] for i in range(4)}

In [45]:
s = set([0, 1, 2])

In [50]:
a[[1, 2,3]]

array([[0.24414217, 0.27054947, 0.18831002],
       [0.93093494, 0.70918501, 0.57479926],
       [0.59712742, 0.99133368, 0.55762764]])

In [59]:
d[0].extend([1,2,3])

In [60]:
d[0]

[0, 2, [1, 2, 3], 1, 2, 3]