In [1]:
import numpy as np

In [10]:
a = np.random.rand(2, 6)

In [14]:
b = np.random.rand(5, 2)

In [16]:
a.dot(np.vstack((np.ones(b.shape[1]), b)))

array([[ 1.29258237,  1.38095596],
       [ 2.16460902,  1.71313361]])

In [9]:
np.vstack(([1], b))

array([[ 1.        ],
       [ 0.95654875],
       [ 0.67824191],
       [ 0.9339112 ],
       [ 0.49757895],
       [ 0.90957201]])

In [11]:
a

array([[ 0.61296034,  0.96098488,  0.04863375,  0.40758963,  0.11848043,
         0.18256049],
       [ 0.87627245,  0.92540414,  0.40382321,  0.33844959,  0.99179884,
         0.24776093]])

In [17]:
b

array([[ 0.25753235,  0.32124616],
       [ 0.40941663,  0.01866858],
       [ 0.54523717,  0.78280095],
       [ 0.532248  ,  0.09390174],
       [ 0.69528672,  0.70216691]])

In [19]:
b[b > 0.5]

array([ 0.54523717,  0.78280095,  0.532248  ,  0.69528672,  0.70216691])

In [21]:
np.maximum(b, 0.5)

array([[ 0.5       ,  0.5       ],
       [ 0.5       ,  0.5       ],
       [ 0.54523717,  0.78280095],
       [ 0.532248  ,  0.5       ],
       [ 0.69528672,  0.70216691]])

In [129]:
def f(x):
    e = np.exp(x)
    return e / np.sum(e, axis = 1, keepdims = True)

In [113]:
b

array([[ 0.25753235,  0.32124616],
       [ 0.40941663,  0.01866858],
       [ 0.54523717,  0.78280095],
       [ 0.532248  ,  0.09390174],
       [ 0.69528672,  0.70216691]])

In [130]:
f(b)

array([[ 0.48407693,  0.51592307],
       [ 0.59646276,  0.40353724],
       [ 0.4408868 ,  0.5591132 ],
       [ 0.60786491,  0.39213509],
       [ 0.49827996,  0.50172004]])

In [116]:
fb = f(b*100)

In [120]:
ans = np.random.randint(0, 2, 5)

In [122]:
np.log(fb[np.arange(fb.shape[0]), ans])

array([ -1.70833641e-03,  -3.90748050e+01,  -2.37563788e+01,
        -4.38346260e+01,  -1.09519644e+00])

In [126]:
logits_for_answers = b[np.arange(len(b)),ans]
np.log(np.sum(np.exp(b),axis=-1))

array([ 0.98304378,  0.92615509,  1.36420428,  1.03005061,  1.39187991])

In [40]:
s = np.random.rand(3, 7+1)

In [44]:
s[0] = 0

In [45]:
s

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [43]:
s[:,0]

array([ 0.,  0.,  0.])

In [46]:
s

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [76]:
x = np.random.rand(5, 13)

In [80]:
x[[1, 2]]

array([[ 0.70139852,  0.74261712,  0.77287786,  0.65088043,  0.84731673,
         0.28329814,  0.42835626,  0.18796173,  0.56908266,  0.47841047,
         0.29190225,  0.92960048,  0.84951128],
       [ 0.44730722,  0.99520102,  0.55740786,  0.96947115,  0.19093646,
         0.77563598,  0.03973888,  0.26001798,  0.8771352 ,  0.07527829,
         0.5967574 ,  0.73757422,  0.12097923]])

In [82]:
np.concatenate((np.ones((x[[1, 2]].shape[0], 1)), x[[1, 2]] ), axis=1)

array([[ 1.        ,  0.70139852,  0.74261712,  0.77287786,  0.65088043,
         0.84731673,  0.28329814,  0.42835626,  0.18796173,  0.56908266,
         0.47841047,  0.29190225,  0.92960048,  0.84951128],
       [ 1.        ,  0.44730722,  0.99520102,  0.55740786,  0.96947115,
         0.19093646,  0.77563598,  0.03973888,  0.26001798,  0.8771352 ,
         0.07527829,  0.5967574 ,  0.73757422,  0.12097923]])

In [54]:
np.matmul(x, s)

array([[ 0.        ,  0.85858936,  0.89529084,  0.33407949,  0.58032953,
         0.6291842 ,  0.85369377,  0.82289268],
       [ 0.        ,  1.05366158,  1.00658112,  0.39577138,  0.77512083,
         1.00311177,  0.80220355,  1.18304637]])

In [84]:
len(x[0].shape)

1

In [93]:
l = np.random.rand(3)

In [92]:
s.shape

(3, 8)

In [91]:
l.reshape(1, 12)

array([[ 0.66165796,  0.21999127,  0.08523696,  0.63347049,  0.19333835,
         0.18629867,  0.04812871,  0.98774806,  0.96409177,  0.92131232,
         0.24010704,  0.20780351]])

In [95]:
np.dot(l, s)

(8,)

In [97]:
x[0]

array([ 0.89804303,  0.68344066,  0.83380986,  0.78875313,  0.19695844,
        0.51743835,  0.92277114,  0.89955622,  0.48283017,  0.22606134,
        0.93770146,  0.27012977,  0.77248989])

In [100]:
np.dot(x[0].reshape(13, 1), np.dot(l, s).reshape(1, 8)).shape

(13, 8)

In [106]:
s * (s > 0.8)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.        ,  0.        ,
         0.        ,  0.9683084 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.84957902,  0.        ,  0.93481514]])

In [107]:
s

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [127]:
np.zeros_like(s)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [128]:
[1] + [2]

[1, 2]

In [134]:
s[0:9]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [150]:
class Layer:
    def __init__(self):
        """Here you can initialize layer parameters (if any) and auxiliary stuff."""
        # A dummy layer does nothing
        self.weights = np.zeros(shape=(input.shape[1], 10))
        bias = np.zeros(shape=(10,))
        pass
    
    def forward(self, input):
        """
        Takes input data of shape [batch, input_units], returns output data [batch, 10]
        """
        output = np.matmul(input, self.weights) + bias
        return output

class Dense(Layer):
    def __init__(self, input_units, output_units, learning_rate=0.1):
        self.learning_rate = learning_rate
        
        # initialize weights with small random numbers. We use normal initialization
        self.weights = np.random.randn(input_units, output_units)*0.01
        self.biases = np.zeros(output_units)
        
    def forward(self,input):
        return np.matmul(input, self.weights) + self.biases
      
    def backward(self,input,grad_output):
        # compute d f / d x = d f / d dense * d dense / d x
        # where d dense/ d x = weights transposed
        grad_input = np.dot(grad_output,np.transpose(self.weights))

        # compute gradient w.r.t. weights and biases
        grad_weights = np.transpose(np.dot(np.transpose(grad_output),input))
        grad_biases = np.sum(grad_output, axis = 0)
        
        # Here we perform a stochastic gradient descent step. 
        # Later on, you can try replacing that with something better.
        self.weights = self.weights - self.learning_rate * grad_weights
        self.biases = self.biases - self.learning_rate * grad_biases
        return grad_input

class ReLU(Layer):
    def __init__(self):
        """ReLU layer simply applies elementwise rectified linear unit to all inputs"""
        pass
    
    def forward(self, input):
        """Apply elementwise ReLU to [batch, input_units] matrix"""
        return np.maximum(0,input)

    def backward(self, input, grad_output):
        """Compute gradient of loss w.r.t. ReLU input"""
        relu_grad = input > 0
        return grad_output*relu_grad 

def softmax_crossentropy_with_logits(logits,reference_answers):
    """Compute crossentropy from logits[batch,n_classes] and ids of correct answers"""
    logits_for_answers = logits[np.arange(len(logits)),reference_answers]
    
    xentropy = - logits_for_answers + np.log(np.sum(np.exp(logits),axis=-1))
    
    return xentropy

def grad_softmax_crossentropy_with_logits(logits,reference_answers):
    """Compute crossentropy gradient from logits[batch,n_classes] and ids of correct answers"""
    ones_for_answers = np.zeros_like(logits)
    ones_for_answers[np.arange(len(logits)),reference_answers] = 1
    
    softmax = np.exp(logits) / np.exp(logits).sum(axis=-1,keepdims=True)
    
    return (- ones_for_answers + softmax) / logits.shape[0]

In [151]:
network = []
network.append(Dense(4,100))
network.append(ReLU())
network.append(Dense(100,200))
network.append(ReLU())
network.append(Dense(200,2))
X = np.random.randn(50, 4)
y = [(0 if x[0] > x[2]**2 or x[3]**3 > 0.5 else 1) for x in X]

In [152]:
def forward(network, X):
    """
    Compute activations of all network layers by applying them sequentially.
    Return a list of activations for each layer. 
    Make sure last activation corresponds to network logits.
    """
    activations = []
    input = X
    for i in range(len(network)):
        activations.append(network[i].forward(X))
        X = network[i].forward(X)
        
    assert len(activations) == len(network)
    return activations

def predict(network,X):
    """
    Compute network predictions.
    """
    logits = forward(network,X)[-1]
    return logits.argmax(axis=-1)

def train(network,X,y):
    """
    Train your network on a given batch of X and y.
    You first need to run forward to get all layer activations.
    Then you can run layer.backward going from last to first layer.
    After you called backward for all layers, all Dense layers have already made one gradient step.
    """
    
    # Get the layer activations
    layer_activations = forward(network,X)
    logits = layer_activations[-1]
    
    # Compute the loss and the initial gradient
    loss = softmax_crossentropy_with_logits(logits,y)
    loss_grad = grad_softmax_crossentropy_with_logits(logits,y)
    
    for i in range(1, len(network)):
        loss_grad = network[len(network) - i].backward(layer_activations[len(network) - i - 1], loss_grad)
    
    return np.mean(loss)
  

In [153]:
for epoch in range(25):
    train(network,X,y)

In [154]:
predict(network, X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1], dtype=int64)

In [156]:
ss = s

In [157]:
s

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [158]:
ss

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.8665626 ,  0.94364583,  0.34335892,  0.55836137,
         0.53463135,  0.9683084 ,  0.75525524],
       [ 0.        ,  0.72816805,  0.63327626,  0.26389163,  0.57827644,
         0.84957902,  0.38824737,  0.93481514]])

In [159]:
ss[1,1] = 88888

In [160]:
ss

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   8.88880000e+04,   9.43645832e-01,
          3.43358925e-01,   5.58361373e-01,   5.34631349e-01,
          9.68308401e-01,   7.55255235e-01],
       [  0.00000000e+00,   7.28168050e-01,   6.33276264e-01,
          2.63891630e-01,   5.78276442e-01,   8.49579017e-01,
          3.88247374e-01,   9.34815140e-01]])

In [164]:
len(s)

3